import type { Metadata, Viewport } from 'next'
import { dmMono, inter, marcellus } from './fonts'
import { THEME_BOOTSTRAP } from '@/lib/theme'
import { OfflineBanner } from '@/components/ui/offline-banner'
import './globals.css'

function siteOrigin(): string {
  const explicit = process.env['NEXT_PUBLIC_SITE_ORIGIN']
  if (explicit !== undefined && explicit !== '') return explicit
  const vercel = process.env['VERCEL_PROJECT_PRODUCTION_URL']
  if (vercel !== undefined && vercel !== '') return `https://${vercel}`
  return 'http://localhost:3000'
}

/**
 * NOTE THE ABSENCE OF an `icons` KEY, WHICH IS DELIBERATE.
 *
 * Next merges the `app/icon.*` and `app/apple-icon.*` file conventions into the resolved
 * metadata only when `icons` is undefined — the merge is guarded by `if (!resolvedMetadata
 * .icons)`. Declaring the key here, even partially, silently DELETES every tag those files
 * would have produced. `favicon.ico` is special-cased and survives; nothing else does.
 *
 * So it is file conventions or `metadata.icons`, never both. This app uses the files:
 * `icon.svg`, `favicon.ico` and `apple-icon.png` all live in this directory and are
 * generated by `pnpm brand:assets`. `openGraph` and `manifest` are unaffected by that rule.
 */
export const metadata: Metadata = {
  /* Resolves the social card to an absolute URL. Read from the environment rather than
     hardcoded: `cloakcal.com` is registered but not yet attached to the project, so writing
     it here would point every unfurl at a host that currently fails its TLS handshake.
     Vercel sets VERCEL_PROJECT_PRODUCTION_URL to whatever the production domain actually is,
     which follows the apex the moment it IS attached. */
  metadataBase: new URL(siteOrigin()),
  // No `template` here. The four pages below already end their own titles with "— CloakCal",
  // so a template would render "Sign in — CloakCal — CloakCal".
  title: 'CloakCal',
  description: 'Not everything is for everyone.',
  applicationName: 'CloakCal',
  manifest: '/manifest.webmanifest',
  openGraph: {
    type: 'website',
    siteName: 'CloakCal',
    title: 'CloakCal',
    description: 'Not everything is for everyone. Your time. Your business.',
  },
  twitter: { card: 'summary_large_image' },
}

export const viewport: Viewport = {
  themeColor: '#0b0d14',
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
}

/**
 * Root layout — a Server Component, and deliberately incapable of decryption.
 * It never imports the crypto or cloak-store packages; the static rule enforces that.
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    /* The font variables go on <html>, and that placement is load-bearing.
       `globals.css` styles `html, body { font-family: var(--font-sans) }`, and `--font-sans`
       is declared on `:root`. Putting the class on <body> instead would leave <html> unable
       to see `--font-inter`, so it would fall through to the literal family name 'Inter' —
       which names nothing, because next/font hashes it. The result is every screen rendering
       in the system font while looking exactly like a font that failed to download. The Dial
       faces ride the same class for the same reason: --font-display and --font-numeral
       resolve on :root, so <html> must be able to see their variables. */
    <html
      lang="en"
      data-theme="dark"
      className={`${inter.variable} ${marcellus.variable} ${dmMono.variable}`}
    >
      <head>
        {/* Applies the stored theme BEFORE first paint.
            The server cannot know which theme this visitor chose — the preference is in
            localStorage — so without this the page paints dark, hydrates, and snaps to light.
            On a calendar of pastel blocks that is a full-screen white flash on every
            navigation, which is worse than not offering the choice at all.
            Inline and synchronous by necessity: anything deferred loses the race to paint. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP }} />
      </head>
      <body>
        <a className="skip-link" href="#main">
          Skip to calendar
        </a>
        {/* Renders nothing while online. In the layout so every page gets it — losing the
            network matters on the auth screens exactly as much as on the calendar. */}
        <OfflineBanner />
        {children}
      </body>
    </html>
  )
}
