import type { Metadata, Viewport } from 'next'
import { headers } from 'next/headers'
import { dmMono, inter, marcellus } from './fonts'
import { NONCE_HEADER } from '@/lib/csp'
import { THEME_BOOTSTRAP } from '@/lib/theme'
import { OfflineBanner } from '@/components/ui/offline-banner'
import './globals.css'

function siteOrigin(): string {
  const explicit = process.env['NEXT_PUBLIC_SITE_ORIGIN']
  if (explicit !== undefined && explicit !== '') return explicit
  const vercel = process.env['VERCEL_PROJECT_PRODUCTION_URL']
  if (vercel !== undefined && vercel !== '') return `https://${vercel}`
  return 'http://localhost:3000'
}

/**
 * NOTE THE ABSENCE OF an `icons` KEY, WHICH IS DELIBERATE.
 *
 * Next merges the `app/icon.*` and `app/apple-icon.*` file conventions into the resolved
 * metadata only when `icons` is undefined — the merge is guarded by `if (!resolvedMetadata
 * .icons)`. Declaring the key here, even partially, silently DELETES every tag those files
 * would have produced. `favicon.ico` is special-cased and survives; nothing else does.
 *
 * So it is file conventions or `metadata.icons`, never both. This app uses the files:
 * `icon.svg`, `favicon.ico` and `apple-icon.png` all live in this directory and are
 * generated by `pnpm brand:assets`. `openGraph` and `manifest` are unaffected by that rule.
 */
export const metadata: Metadata = {
  /* Resolves the social card to an absolute URL. Read from the environment rather than
     hardcoded: `cloakcal.com` is registered but not yet attached to the project, so writing
     it here would point every unfurl at a host that currently fails its TLS handshake.
     Vercel sets VERCEL_PROJECT_PRODUCTION_URL to whatever the production domain actually is,
     which follows the apex the moment it IS attached. */
  metadataBase: new URL(siteOrigin()),
  // No `template` here. The four pages below already end their own titles with "— CloakCal",
  // so a template would render "Sign in — CloakCal — CloakCal".
  title: 'CloakCal',
  /*
   * SAYS WHAT IT IS, because a description is not a tagline. This was
   * 'Not everything is for everyone.' -- fine above a hero that explains itself, and the
   * only thing a search result or a link unfurl had to go on. Neither ever said the word
   * calendar.
   *
   * Bound by rule 1 like every other claim: what is encrypted is the CONTENT, and the
   * sentence says so rather than implying the whole event is sealed.
   */
  description:
    'A calendar that shows different people different amounts of the same event. Titles, places and notes are encrypted in your browser.',
  applicationName: 'CloakCal',
  manifest: '/manifest.webmanifest',
  openGraph: {
    type: 'website',
    siteName: 'CloakCal',
    title: 'CloakCal',
    description:
      'A calendar that shows different people different amounts of the same event. Titles, places and notes are encrypted in your browser.',
  },
  twitter: { card: 'summary_large_image' },
}

export const viewport: Viewport = {
  themeColor: '#0b0d14',
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
}

/**
 * Root layout — a Server Component, and deliberately incapable of decryption.
 * It never imports the crypto or cloak-store packages; the static rule enforces that.
 */
/**
 * Reading a header here opts the ENTIRE APP out of static generation, and that is accepted
 * rather than overlooked.
 *
 * A per-request nonce cannot exist in a page rendered once at build time, so static rendering
 * and a nonce-based CSP are mutually exclusive — there is no arrangement that keeps both.
 * The cost is `/sign-in`, `/sign-up`, `/recover` and `/robots.txt`, which were the only
 * prerendered routes left; everything else already reads a session or searchParams. For a
 * private calendar with sign-ups closed that is a rounding error, and the alternative is
 * serving the weakest policy on the three pages that handle passwords.
 *
 * The visible consequence: `build-output.leak.test.ts` can no longer scan prerendered HTML or
 * RSC payloads, because none are emitted. Those assertions moved to `e2e/leak.spec.ts`, which
 * reads what is actually rendered. They were written to FAIL rather than skip on missing
 * input, which is why this change announced itself instead of quietly gutting a privacy gate.
 */
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Undefined when middleware did not run — nothing serves this app that way today, but a
  // missing nonce must degrade to "no nonce attribute" rather than to the string
  // "undefined", which would be a nonce the CSP does not name and therefore a blocked script.
  const nonce = (await headers()).get(NONCE_HEADER) ?? undefined

  return (
    /* The font variables go on <html>, and that placement is load-bearing.
       `globals.css` styles `html, body { font-family: var(--font-sans) }`, and `--font-sans`
       is declared on `:root`. Putting the class on <body> instead would leave <html> unable
       to see `--font-inter`, so it would fall through to the literal family name 'Inter' —
       which names nothing, because next/font hashes it. The result is every screen rendering
       in the system font while looking exactly like a font that failed to download. The Dial
       faces ride the same class for the same reason: --font-display and --font-numeral
       resolve on :root, so <html> must be able to see their variables. */
    <html
      lang="en"
      data-theme="dark"
      className={`${inter.variable} ${marcellus.variable} ${dmMono.variable}`}
    >
      <head>
        {/* Applies the stored theme BEFORE first paint.
            The server cannot know which theme this visitor chose — the preference is in
            localStorage — so without this the page paints dark, hydrates, and snaps to light.
            On a calendar of pastel blocks that is a full-screen white flash on every
            navigation, which is worse than not offering the choice at all.
            Inline and synchronous by necessity: anything deferred loses the race to paint. */}
        {/*
          `suppressHydrationWarning` IS ABOUT THE BROWSER, NOT ABOUT THIS MARKUP, and it is the
          one place in this app where suppressing a hydration warning is the correct answer
          rather than a way of not looking at one.

          Browsers deliberately BLANK the `nonce` content attribute once the CSP has been
          applied. It is an anti-exfiltration measure: without it a stylesheet could read the
          nonce out one character at a time with `script[nonce^="a"]` selectors and hand a
          would-be injector the only thing standing between them and a script tag. The real
          value survives in the element's internal slot, which is what the browser enforces
          against; `getAttribute('nonce')` returns "".

          React hydrates by comparing attributes, so it saw the server's nonce against an empty
          string and reported a mismatch on EVERY ROUTE, in every browser, for the life of the
          nonce-based CSP. Nothing was wrong with the output and nothing could be done to the
          output to fix it.

          Left alone it is worse than noise. A permanent error in every console is where a real
          hydration bug goes to hide, and this app has already paid once for a genuine failure
          that looked like ordinary breakage (the doubled `/settings` page). Scoped to this one
          element, so any other mismatch still shouts.
        */}
        <script
          nonce={nonce}
          suppressHydrationWarning
          dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP }}
        />
      </head>
      <body>
        <a className="skip-link" href="#main">
          Skip to calendar
        </a>
        {/* Renders nothing while online. In the layout so every page gets it — losing the
            network matters on the auth screens exactly as much as on the calendar. */}
        <OfflineBanner />
        {children}
      </body>
    </html>
  )
}
